#development version of configuration

server:
  port: 8083

#  Database Connection

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_app_yt
    username: postgres
    password: Ruhul@2002

    #    hikari:
    #      pool-name: HikariCP              # Connection pool name
    #      maximum-pool-size: 5             # Maximum 5 DB connections
    #      connection-timeout: 10000        # Wait 10 sec for connection
    #      idle-timeout: 600000             # Remove idle connection after 10 min
    #      max-lifetime: 1800000            # Maximum connection lifetime: 30 min
    #      validation-timeout: 1800000      # Timeout for connection validation
    #      leak-detection-threshold: 0      # Disable connection leak detection
    #      initialization-fail-timeout: -1  # Don't fail startup if DB is unavailable

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Modern Hibernate/Spring Boot automatically detects the database dialect from the JDBC connection, so we usually don't need to specify it manually.
        format_sql: true
    show-sql: true  # means Spring Boot will display the SQL queries executed by Hibernate in the console.


# this line written to visual the error of the code in console
logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
     secret: ${JWT_SECRET:saiofal;vkasfbehwqpofhjashofjaswfpojasfvbafop[hfifonfo[shjfwefjjfslajfsahfoshfffasnbash[f} # TODO This makes your application more secure and easier to deploy across different environments without changing the source code.
     issuer: ${JWT_ISSUER:api.substring.com}
     access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
     refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
     refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
     cookie-secure: ${JWT_COOKIE_SECURE:true}
     cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
     cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
